=== perftool-incubator/rickshaw/util/JSON/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "schema": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "enum": [
                        "2023.09.27"
                    ]
                }
            }
        },
        "tags": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "endpoints": {
            "type": "array",
            "items": {
                "minItems": 1,
                "type": "object"
            }
        },
        "tool-params": {
            "type": "array",
            "items": {
                "minItems": 0,
                "type": "object"
            }
        },
        "run-params": {
            "type": "object",
	    "properties": {
		"num-samples": {
		    "type": "integer",
		    "minimum": 1
		},
		"max-sample-failures": {
		    "type": "integer",
		    "minimum": 1
		},
		"test-order": {
		    "type": "string",
		    "enum": [
			"s",
			"sample",
			"i",
			"iteration",
			"r",
			"random"
		    ]
		},
		"name": {
		    "type": "string",
		    "minLength": 1
		},
		"email": {
		    "type": "string",
		    "minLength": 1
		}
	    },
	    "dependentRequired": {
		"name": ["email"],
		"email": ["name"]
	    },
	    "additionalProperties": false,
	    "required": []
        },
        "benchmarks": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },  
                    "ids": {
			"$ref": "#/definitions/number-lists"
                    },
                    "mv-params": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "minItems": 1,
                                    "type": "object"
                                }
                            },
                            {
                                "type": "object"
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "ids",
                    "mv-params"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "benchmarks"
    ],
    "definitions": {
        "number-lists": {
            "anyOf": [
                {
                    "type": "string",
                    "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)(\\+(([1-9][0-9]*)(-[1-9][0-9]*)?))*$"
                },
                {
                    "type": "integer"
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "anyOf": [
                            {
                                "type": "string",
                                "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)$"
                            },
                            {
                                "type": "integer"
                            }
                        ]
                    }
                }
            ]
        }
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/cyclictest.remotehost.json
{
    "benchmarks": [
        {
            "name": "cyclictest",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "priority", "vals": [ "1", "2" ], "role": "client" },
                            { "arg": "smi", "vals": [ "off" ], "role": "client" }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "cyclictest-remotehost-run-file-json"
    },
    "endpoints": [
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": "1",
            "client": "1-2",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" },
                        { "role": "server", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "2" }
                    ],
                   "settings": {
                        "osruntime": "chroot"
                    }
                },
                {
                   "targets": "default",
                   "settings": {
                        "cpu-partitioning": "1"
                    }
                }             
            ]
        },
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "profiler": "1",
            "config": [
                {
                    "targets": [
                        { "role": "profiler", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "chroot"
                    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/tests/JSON/input-multibench-k8s-remotehosts.json
{
    "benchmarks": [
        {
            "name": "oslat",
            "ids": "1-2",
            "mv-params": {
                "sets": [
                    {
                        "params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "rtprio", "vals": [ "1" ], "role": "client" }
                        ]
                    }
                ]
            }
        },
        {
            "name": "uperf",
            "ids": ["3-4","6-7"],
            "mv-params": {
                "sets": [
                    {
                        "params": [
                            { "arg": "ifname", "vals": ["eth0"], "role": "server" },
                            { "arg": "ipv", "vals": ["6"], "role": "all" },
                            { "arg": "protocol", "vals": ["udp"], "id": "21" },
                            { "arg": "bitrate", "vals": ["200M"], "id": "21" },
                            { "arg": "length", "vals": ["256"], "id": "21" }
                        ]
                    }
                ]

            }
        },
        {
            "name": "iperf",
            "ids": "5",
            "mv-params": {
                "global-options": [
                    {
                        "name": "common-params",
                        "params": [
                            { "arg": "duration", "vals": ["60"] },
                            { "arg": "protocol", "vals": ["tcp"] },
                            { "arg": "nthreads", "vals": ["1"] },
                            { "arg": "ifname", "vals": ["eth0"], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "common-params",
                        "params": [
                            { "arg": "test-type", "vals": ["crr"], "id": "1" },
                            { "arg": "wsize", "vals": ["512"], "id": "1" },
                            { "arg": "rsize", "vals": ["2048"], "id": "1" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "run": "multibench-runfile"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "K8S_CONTROLLER_IP",
            "host": "K8S_ENDPOINT_HOST",
            "user": "K8S_ENDPOINT_USER",
            "userenv": "alma8",
            "unique-project": 1,
            "kubeconfig": 0,
            "server": "1-7",
            "client": "2-4+6",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "2" },
                        { "role": "server", "ids": "1+3+5" }
                    ],
                    "settings": {
                        "securityContext": {
                            "capabilities": {
                                "add": [ "SYS_NICE", "IPC_LOCK" ]
                            }
                        },
                        "nodeSelector": {
                            "kubernetes.io/hostname": "worker-001"
                        }
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "3-4+6" },
                        { "role": "server", "ids": "2+4+6-7" }
                    ],
                    "settings": {
                        "nodeSelector": {
                            "kubernetes.io/hostname": "worker-002"
                        }
                    }
                },
                {
                    "targets": "all",
                    "settings": {
                        "cpu-partitioning": 1
                    }
                }
            ]
        },
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "ENDPOINT_USER"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1, 5 ] }
		    ],
		    "config": {
			"host": "ENDPOINT_HOST"
		    }
		}
	    ]
	}
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/oslat.kube.json
{
    "benchmarks": [
        {
            "name": "oslat",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "common-params",
                        "params": [
                            { "arg": "duration", "vals": [ "10", "15" ], "role": "client" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "common-params"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "oslat-kube-run-file-json"
    },
    "endpoints": [
	{
	    "type": "kube",
	    "controller-ip-address": "CONTROLLER_IP",
	    "host": "CI_ENDPOINT_HOST",
	    "user": "CI_ENDPOINT_USER",
	    "engines": {
		"server": 1,
		"client": 1
	    },
	    "config": [
		{
		    "targets": [
                        { "role": "client", "ids": 1 }
		    ],
                    "settings": {
                        "securityContext": {
                            "container": {
                                "capabilities": {
                                    "add": [ "SYS_NICE", "IPC_LOCK" ]
                                }
                            }
                        }
                    }
		},
		{
                    "targets": "default",
                    "settings": {
                        "cpu-partitioning": true
                    }
		}
	    ]
	}
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/iperf.remotehosts.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
			    { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "iperf-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] },
			{ "role": "server", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] },
			{ "role": "server", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/iperf.kube.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
			    { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "iperf-kube-run-file-json"
    },
    "endpoints": [
	{
	    "type": "kube",
	    "controller-ip-address": "CONTROLLER_IP",
	    "host": "CI_ENDPOINT_HOST",
	    "user": "CI_ENDPOINT_USER",
	    "engines": {
		"server": "1-2",
		"client": "1-2"
	    }
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/uperf.kube.json
{
    "benchmarks": [
        {
            "name": "uperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
                            { "arg": "wsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "rsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
                            { "arg": "nthreads", "vals": [ "1", "8" ], "role": "client" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "uperf-kube-run-file-json"
    },
    "endpoints": [
	{
	    "type": "kube",
	    "controller-ip-address": "CONTROLLER_IP",
	    "host": "CI_ENDPOINT_HOST",
	    "user": "CI_ENDPOINT_USER",
	    "engines": {
		"server": "1-2",
		"client": "1-2"
	    }
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/multi.kube.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "time", "vals": [ "10" ], "role": "client" },
                            { "arg": "protocol", "vals": [ "tcp" ] },
                            { "arg": "bitrate", "vals": [ "0" ] },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        },
        {
            "name": "uperf",
            "ids": "2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
                            { "arg": "wsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "rsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
                            { "arg": "nthreads", "vals": [ "1", "8" ], "role": "client" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "multibench-kube-run-file-json"
    },
    "endpoints": [
	{
	    "type": "kube",
	    "controller-ip-address": "CONTROLLER_IP",
	    "host": "CI_ENDPOINT_HOST",
	    "user": "CI_ENDPOINT_USER",
	    "engines": {
		"server": "1-2",
		"client": "1-2"
	    }
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/cyclictest.kube.json
{
    "benchmarks": [
        {
            "name": "cyclictest",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "priority", "vals": [ "1", "2" ], "role": "client" },
                            { "arg": "smi", "vals": [ "off" ], "role": "client" }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "cyclictest-kube-run-file-json"
    },
    "endpoints": [
        {
            "type": "kube",
            "controller-ip-address": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
	    "engines": {
		"server": 1,
		"client": "1-2"
	    },
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1-2" }
                    ],
                    "settings": {
                        "securityContext": {
                            "container": {
                                "privileged": true
                            }
                        }
                    }
                },
                {
                    "targets": "default",
                    "settings": {
                        "cpu-partitioning": true
                    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}
