=== perftool-incubator/rickshaw/util/JSON/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "schema": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "enum": [
                        "2023.09.27"
                    ]
                }
            }
        },
        "tags": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "endpoints": {
            "type": "array",
            "items": {
                "minItems": 1,
                "type": "object"
            }
        },
        "tool-params": {
            "type": "array",
            "items": {
                "minItems": 0,
                "type": "object"
            }
        },
        "run-params": {
            "type": "object",
	    "properties": {
		"num-samples": {
		    "type": "integer",
		    "minimum": 1
		},
		"max-sample-failures": {
		    "type": "integer",
		    "minimum": 1
		},
		"test-order": {
		    "type": "string",
		    "enum": [
			"s",
			"sample",
			"i",
			"iteration",
			"r",
			"random"
		    ]
		},
		"name": {
		    "type": "string",
		    "minLength": 1
		},
		"email": {
		    "type": "string",
		    "minLength": 1
		}
	    },
	    "dependentRequired": {
		"name": ["email"],
		"email": ["name"]
	    },
	    "additionalProperties": false,
	    "required": []
        },
        "benchmarks": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },  
                    "ids": {
			"$ref": "#/definitions/number-lists"
                    },
                    "mv-params": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "minItems": 1,
                                    "type": "object"
                                }
                            },
                            {
                                "type": "object"
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "ids",
                    "mv-params"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "benchmarks"
    ],
    "definitions": {
        "number-lists": {
            "anyOf": [
                {
                    "type": "string",
                    "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)(\\+(([1-9][0-9]*)(-[1-9][0-9]*)?))*$"
                },
                {
                    "type": "integer"
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "anyOf": [
                            {
                                "type": "string",
                                "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)$"
                            },
                            {
                                "type": "integer"
                            }
                        ]
                    }
                }
            ]
        }
    }
}

=== perftool-incubator/rickshaw/util/crucible-ci/fio.remotehosts.json
{
    "benchmarks": [
        {
            "name": "fio",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "clocksource", "vals": [ "gettimeofday" ] },
			    { "arg": "ramp_time", "vals": [ "5s" ] },

			    { "arg": "bs", "vals": [ "4K", "512K" ] },
			    { "arg": "unlink", "vals": [ "1" ] },
			    { "arg": "filename", "vals": [ "/tmp/fio.foo" ] },
			    { "arg": "runtime", "vals": [ "10s" ] },
			    { "arg": "time_based", "vals": [ "1" ] },
			    { "arg": "norandommap", "vals": [ "ON" ] },
			    { "arg": "rw", "vals": [ "randrw" ] },
			    { "arg": "ioengine", "vals": [ "sync" ] },
			    { "arg": "size", "vals": [ "10M" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        },
        {
            "tool": "forkstat"
        }
    ],
    "tags": {
        "description": "fio-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}
